services:
  pgdatabase:
    image: postgres:14.1
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
    -  "./ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
    ports:
    - "5050:5432"
    networks:
    - postgres
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.net
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
    - "8080:80"
    networks:
    - postgres
networks:
  postgres:
    driver: bridge
